### PR TITLE
Updated ArduinoJson to V6

### PR DESCRIPTION
**Pull request by ReneHezser**
Updated to ArduinoJson V6.
(sry about the different formatting. VSCode did it this way for me)

### CODE REVIEW

**Comment by nrwiersma** [comment]
Wow. Thanks very much for the contribution. Will check it it out asap. @cgmckeever, would like your opinion as well.

**Comment by ReneHezser** [comment]
Yes please. I am a noob with cpp

**Comment by nrwiersma** [comment]
@ReneHezser  Would you mind terribly if I put the formatting back to what it was?

**Comment by ReneHezser** [comment]
Not at all. Please modify everything that needs to be modified. Even if it is just the formatting ;-)

**Comment by cgmckeever** [comment]
Looks solid -- I will once over again once the diff is smaller with the formatting change back 👍

**Comment by nrwiersma** [comment]
So i fixed your commit, not realising it was on your master branch. Sorry.

**Comment by nrwiersma** [comment]
I will fix it

**Comment by nrwiersma** [comment]
do me a favour and make a branch `update-json` please.

**Comment by nrwiersma** [comment]
Moved to #78. Sorry for the brain fart.

**Pull request closed without merging**
