### PR TITLE
Organize methods for better human parse

### PR DESCRIPTION
**Pull request by cgmckeever**
@nrwiersma 👋  ... Im going to `try` to separate out the http server from the logic. Im doing this as something I am working on already has a conflicting web server. In order to not make the PR look like a mess, I first organized the `.cpp` so my brain can grok it better as I attempt to peel the pieces. No code should have changed in this PR, only shuffle

### CODE REVIEW

**Comment by nrwiersma** [comment]
Thanks very much. It is basically impossible to see what is happening in the review 😄 so I will take your word for it.

**Comment by nrwiersma** [comment]
Are there other PRs coming?

**Comment by cgmckeever** [comment]
Hey man -- hope all is well .. IF I can get it to where i need it, yes .. BUT, Im not about to machine gun a bunch today ;)

**Comment by nrwiersma** [comment]
Hey. All good thanks. Hope you are well too. I will leave this unversioned for now. Let me know when you are done.

**Comment by cgmckeever** [comment]
> Thanks very much. It is basically impossible to see what is happening in the review 😄 so I will take your word for it.

Yeah, as I started to think about how I want to approach this, and looking at the `areas` of code, I was like, there is no way Im going to peel this apart in a way that will not make @nrwiersma go nuts with code shuffle --- so I just did this re-org first to get that out of the way -- much appreciated

**Pull request merged**
